global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'telemetry-kitchen'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:9091']
    metrics_path: '/metrics'

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:9092']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
