apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    uid: postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    database: telemetry_kitchen
    user: tk
    secureJsonData:
      password: tk
    jsonData:
      sslmode: disable
      postgresVersion: 1700
    editable: true
