global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'local-dev'
    cluster: 'telemetry-kitchen'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway-poller'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          service: 'gateway-poller'
          component: 'poller'
