global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'local-dev'
    cluster: 'telemetry-kitchen'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway-poller'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          service: 'gateway-poller'
          component: 'poller'

  - job_name: 'postgres'
    scrape_interval: 10s
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'
          component: 'database'

  - job_name: 'rabbitmq'
    scrape_interval: 10s
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: 'rabbitmq'
          component: 'message-broker'

  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          component: 'system'
